# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cbir.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(794, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.central_layout = QtWidgets.QVBoxLayout()
        self.central_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.central_layout.setObjectName("central_layout")
        self.top_layout = QtWidgets.QHBoxLayout()
        self.top_layout.setSpacing(3)
        self.top_layout.setObjectName("top_layout")
        self.top_right_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.top_right_group_box.setObjectName("top_right_group_box")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.top_right_group_box)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.left_widget = SlideListWidget(self.top_right_group_box)
        self.left_widget.setObjectName("left_widget")
        self.verticalLayout_2.addWidget(self.left_widget)
        self.top_layout.addWidget(self.top_right_group_box)
        self.top_left_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.top_left_group_box.setObjectName("top_left_group_box")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.top_left_group_box)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.right_widget = SlideViewer(self.top_left_group_box)
        self.right_widget.setObjectName("right_widget")
        self.verticalLayout_3.addWidget(self.right_widget)
        self.top_layout.addWidget(self.top_left_group_box)
        self.central_layout.addLayout(self.top_layout)
        self.bottom_layout = QtWidgets.QHBoxLayout()
        self.bottom_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.bottom_layout.setSpacing(3)
        self.bottom_layout.setObjectName("bottom_layout")
        self.bottom_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.bottom_group_box.setObjectName("bottom_group_box")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.bottom_group_box)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bottom_widget = SlideListWidget(self.bottom_group_box)
        self.bottom_widget.setEnabled(True)
        self.bottom_widget.setAutoFillBackground(False)
        self.bottom_widget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.bottom_widget.setObjectName("bottom_widget")
        self.verticalLayout_4.addWidget(self.bottom_widget)
        self.bottom_layout.addWidget(self.bottom_group_box)
        self.central_layout.addLayout(self.bottom_layout)
        self.central_layout.setStretch(0, 1)
        self.central_layout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.central_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 794, 21))
        self.menubar.setObjectName("menubar")
        self.db_menu = QtWidgets.QMenu(self.menubar)
        self.db_menu.setObjectName("db_menu")
        self.query_menu = QtWidgets.QMenu(self.menubar)
        self.query_menu.setObjectName("query_menu")
        self.menu_action = QtWidgets.QMenu(self.menubar)
        self.menu_action.setObjectName("menu_action")
        self.results_menu = QtWidgets.QMenu(self.menubar)
        self.results_menu.setObjectName("results_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_slide = QtWidgets.QAction(MainWindow)
        self.actionLoad_slide.setObjectName("actionLoad_slide")
        self.db_action_load = QtWidgets.QAction(MainWindow)
        self.db_action_load.setObjectName("db_action_load")
        self.actionSearch = QtWidgets.QAction(MainWindow)
        self.actionSearch.setObjectName("actionSearch")
        self.actionShow_query_tile = QtWidgets.QAction(MainWindow)
        self.actionShow_query_tile.setObjectName("actionShow_query_tile")
        self.action_search = QtWidgets.QAction(MainWindow)
        self.action_search.setObjectName("action_search")
        self.action_show_query_tile = QtWidgets.QAction(MainWindow)
        self.action_show_query_tile.setObjectName("action_show_query_tile")
        self.query_load_action = QtWidgets.QAction(MainWindow)
        self.query_load_action.setObjectName("query_load_action")
        self.action_select_all_images = QtWidgets.QAction(MainWindow)
        self.action_select_all_images.setObjectName("action_select_all_images")
        self.actionSdf = QtWidgets.QAction(MainWindow)
        self.actionSdf.setObjectName("actionSdf")
        self.actionStuff1 = QtWidgets.QAction(MainWindow)
        self.actionStuff1.setObjectName("actionStuff1")
        self.menubar.addAction(self.db_menu.menuAction())
        self.menubar.addAction(self.query_menu.menuAction())
        self.menubar.addAction(self.menu_action.menuAction())
        self.menubar.addAction(self.results_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.top_right_group_box.setTitle(_translate("MainWindow", "db_models"))
        self.top_left_group_box.setTitle(_translate("MainWindow", "query_slide"))
        self.bottom_group_box.setTitle(_translate("MainWindow", "results"))
        self.db_menu.setTitle(_translate("MainWindow", "db"))
        self.query_menu.setTitle(_translate("MainWindow", "query"))
        self.menu_action.setTitle(_translate("MainWindow", "actions"))
        self.results_menu.setTitle(_translate("MainWindow", "results"))
        self.actionLoad_slide.setText(_translate("MainWindow", "load_slide"))
        self.db_action_load.setText(_translate("MainWindow", "load"))
        self.actionSearch.setText(_translate("MainWindow", "search"))
        self.actionShow_query_tile.setText(_translate("MainWindow", "show query tile"))
        self.action_search.setText(_translate("MainWindow", "search"))
        self.action_show_query_tile.setText(_translate("MainWindow", "show query tile"))
        self.query_load_action.setText(_translate("MainWindow", "load"))
        self.action_select_all_images.setText(_translate("MainWindow", "select all images"))
        self.actionSdf.setText(_translate("MainWindow", "sdf"))
        self.actionStuff1.setText(_translate("MainWindow", "stuff1"))

from slide_list_view_47.widgets.slide_list_widget import SlideListWidget
from slide_viewer_47.widgets.slide_viewer import SlideViewer
